spring.application.name=sales-stock-backend
server.port=${PORT:8080}
spring.datasource.url=jdbc:mysql://mysql-1ce91cef-eanushanhansana-d529.j.aivencloud.com:12993/sales_db?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=<redacted>
#spring.datasource.url=jdbc:mysql://localhost:3306/sales_db?createDatabaseIfNotExist=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# Max file size (increase as needed)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Optional: Configure file size threshold
spring.servlet.multipart.file-size-threshold=2KB

# Optional: Configure location for temporary storage
spring.servlet.multipart.location=/tmp